apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: module3yan-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ''
    path: ''
    targetRevision: ''

    # Manifests for your application
    kustomize:
      images:
        - public.ecr.aws/j8p9i7s1/module3yan:db-48
        - public.ecr.aws/j8p9i7s1/module3yan:back-48
        - public.ecr.aws/j8p9i7s1/module3yan:front-48



  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  # Direct deployment configuration
  sourceType: kustomize
  kustomize:
    images:
      - public.ecr.aws/j8p9i7s1/module3yan:db-48
      - public.ecr.aws/j8p9i7s1/module3yan:back-48
      - public.ecr.aws/j8p9i7s1/module3yan:front-48
