apiVersion: apps/v1
kind: Deployment
metadata:
  name: module3yan-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: module3yan
  template:
    metadata:
      labels:
        app: module3yan
    spec:
      containers:
      - name: db
        image: public.ecr.aws/j8p9i7s1/module3yan:db-48
        ports:
        - containerPort: 3307
        readinessProbe:
          tcpSocket:
            port: 3307
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: back
        image: public.ecr.aws/j8p9i7s1/module3yan:back-48
        env:
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: "3307"
      - name: front
        image: public.ecr.aws/j8p9i7s1/module3yan:front-48
